baseURL = "/"
languageCode = "en-us"
title = "Amply Status"
theme = "cstate"

[permalinks]
    incidents = "/incidents/:year/:month/:day/:slug/"

[params]
    logo = "https://amply.cloud/assets/images/logo.png"
    faviconsPath = "/images/favicon/"
    autoRefresh = true
    useLogo = true
    incidentPostsPerPage = 10
    description = "Amply Services Status"
    brand = "f4f8fb"
    ok = "228B22"
    disrupted = "FF8C00"
    down = "DC143C"
    notice = "708090"
    alwaysKeepBrandColor = true
    googleAnalytics = "UA-124644803-3"
    version = 2

[[params.systems]]
    name = "Road API"
[[params.systems]]
    name = "AMP Render"
[[params.systems]]
    name = "AMP API"
[[params.systems]]
    name = "Status - amply"